DELETE FROM
    surtrics.surplus_metrics_data a
    USING surtrics.surplus_metrics_data b
WHERE
        a.id < b.id
  AND a."user" = b."user"
  AND a.sku = b.sku
  AND a.code = b.code
  AND a.transaction_date = b.transaction_date
  AND a.transaction_type = b.transaction_type
  AND a.quantity = b.quantity
  AND a.location = b.location
  AND a.transaction_type != 'Error'
  AND a.id > 5324330
  RETURNING a.*
;


SELECT id FROM surtrics.surplus_metrics_data ORDER BY id DESC LIMIT 1;