DROP TABLE IF EXISTS surtrics.surplus_sales_data;
CREATE TABLE IF NOT EXISTS surtrics.surplus_sales_data(
    sale_id BIGSERIAL PRIMARY KEY NOT NULL ,
    payment_date timestamp NOT NULL ,
    order_id INT NOT NULL,
    order_status VARCHAR(50) NOT NULL,
    name TEXT NOT NULL,
    store_id INT NOT NULL,
    items text[] NOT NULL
);

SELECT
    *
FROM
    surtrics.surplus_sales_data
WHERE
    DATE(payment_date - interval '2 hours') = '10-23-23'
ORDER BY
    store_id;


